---

name: unstash action
inputs:
  name:
    description: 'Unstash name'
    default: 'unstash'
  path:
    description: 'A directory that describes where to extract stashed files'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download stash
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}

    - name: Extract stash
      run: tar -axf ${{ inputs.name }}.tar.zst -C ${{ inputs.path }}
      shell: bash
