name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.asciidoc'

# limit the access of the generated GITHUB_TOKEN
permissions:
  contents: read

jobs:
  matrix:
    strategy:
      matrix:
        os: ubuntu-latest
        command: [
          "./mvnw clean install -DskipTests=true -Dmaven.javadoc.skip=true",
          "./mvnw org.codehaus.mojo:license-maven-plugin:aggregate-third-party-report -Dlicense.excludedGroups=^co\\.elastic\\.",
          "./mvnw test",
          "./mvnw -q -P ci-non-application-server-integration-tests verify",
          "./mvnw -q -P ci-application-server-integration-tests verify",
          "./mvnw compile javadoc:javadoc"
        ]
        version: 11
        include:
          - os: windows-latest
            command: "mvnw.cmd clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dmaven.gitcommitid.skip=true"
          - os: windows-latest
            command: "mvnw.cmd clean test"
          - version: 17
            command: "./mvnw test"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'adopt'
      - run: ${{ matrix.command }}
